"""Storage foundation for the progress CLI."""

from .database import (
	BUSY_TIMEOUT_SECONDS,
	DEFAULT_DATABASE_PATH,
	Database,
	connect_database,
)
from .errors import (
	AlreadyInitialisedError,
	DatabaseBusyError,
	EmptyValueError,
	GitBindingError,
	InvalidObjectIdError,
	MigrationFailedError,
	NotAProjectError,
	NotFoundError,
	ObjectIdCollisionError,
	OrphanedProjectError,
	ProgressError,
	ProjectBindingRecoveryError,
	StaleSchemaError,
	UninitialisedProjectError,
	WrongObjectIdTypeError,
)
from .ids import (
	CHUNK_PREFIX,
	NOTE_PREFIX,
	PROJECT_PREFIX,
	RELEASE_PREFIX,
	TASK_PREFIX,
	generate_object_id,
	is_valid_object_id,
	validate_object_id,
)
from .projects import Project, ProjectStore

__all__ = [
	"AlreadyInitialisedError",
	"BUSY_TIMEOUT_SECONDS",
	"CHUNK_PREFIX",
	"Database",
	"DatabaseBusyError",
	"DEFAULT_DATABASE_PATH",
	"EmptyValueError",
	"GitBindingError",
	"InvalidObjectIdError",
	"MigrationFailedError",
	"NOTE_PREFIX",
	"NotAProjectError",
	"NotFoundError",
	"ObjectIdCollisionError",
	"OrphanedProjectError",
	"PROJECT_PREFIX",
	"ProgressError",
	"Project",
	"ProjectBindingRecoveryError",
	"ProjectStore",
	"RELEASE_PREFIX",
	"StaleSchemaError",
	"TASK_PREFIX",
	"UninitialisedProjectError",
	"WrongObjectIdTypeError",
	"connect_database",
	"generate_object_id",
	"is_valid_object_id",
	"validate_object_id",
]
